-- Datos de ejemplo de medicamentos para PharmaChat
-- Ejecutar después de la migración inicial

INSERT INTO medicamentos (nombre, principio_activo, categoria, presentacion, dosis_adulta, dosis_pediatrica, contraindicaciones, efectos_secundarios, interacciones, indicaciones) VALUES
(
  'Paracetamol',
  'Acetaminofén',
  'Analgésicos',
  'Tabletas 500mg, Jarabe 120mg/5ml',
  '500-1000mg cada 6-8 horas. Máximo 4g/día.',
  '10-15mg/kg cada 6-8 horas. Máximo 4 dosis/día.',
  'Hepatopatía grave, hipersensibilidad al fármaco, alcoholismo crónico.',
  'Raras en dosis terapéuticas. Sobredosis: hepatotoxicidad grave, náuseas, vómitos.',
  'Alcohol: aumenta riesgo hepatotóxico. Warfarina: puede potenciar efecto anticoagulante.',
  'Fiebre, dolor leve a moderado, cefalea, dolor muscular, odontalgia, dolor postoperatorio.'
),
(
  'Ibuprofeno',
  'Ibuprofeno',
  'Antiinflamatorios',
  'Tabletas 200mg, 400mg, 600mg. Suspensión 100mg/5ml.',
  '200-600mg cada 6-8 horas. Máximo 2400mg/día.',
  '5-10mg/kg cada 6-8 horas. Máximo 40mg/kg/día.',
  'Úlcera péptica activa, insuficiencia renal grave, asma inducida por AINEs, tercer trimestre de embarazo.',
  'Dispepsia, náuseas, dolor abdominal. Raro: sangrado gastrointestinal, nefrotoxicidad, reacciones cutáneas.',
  'Anticoagulantes: aumenta riesgo de sangrado. Antihipertensivos: reduce su efecto. Litio: aumenta niveles séricos.',
  'Dolor e inflamación, artritis reumatoide, osteoartritis, dismenorrea, fiebre, dolor postoperatorio.'
),
(
  'Amoxicilina',
  'Amoxicilina trihidrato',
  'Antibióticos',
  'Cápsulas 250mg, 500mg. Suspensión 250mg/5ml.',
  '250-500mg cada 8 horas. Infecciones graves: 500-1000mg cada 8 horas.',
  '20-40mg/kg/día divididos cada 8 horas.',
  'Hipersensibilidad a penicilinas, mononucleosis infecciosa (riesgo de exantema).',
  'Diarrea, náuseas, exantema cutáneo, candidiasis oral. Raro: reacción alérgica grave.',
  'Metotrexato: aumenta toxicidad. Anticoagulantes orales: puede aumentar INR. Alopurinol: aumenta incidencia de exantema.',
  'Infecciones del tracto respiratorio, otitis media, infecciones urinarias, infecciones de piel y tejidos blandos.'
),
(
  'Omeprazol',
  'Omeprazol',
  'Inhibidores de bomba de protones',
  'Cápsulas 20mg, 40mg.',
  '20-40mg una vez al día, antes del desayuno.',
  '0.5-1mg/kg/día en niños mayores de 1 año.',
  'Hipersensibilidad al omeprazol. No usar con rilpivirina.',
  'Cefalea, diarrea, dolor abdominal, náuseas. Uso prolongado: deficiencia de B12, hipomagnesemia, fracturas.',
  'Clopidogrel: reduce su efecto antiagregante. Diazepam: prolonga su eliminación. Warfarina: puede aumentar efecto.',
  'Reflujo gastroesofágico, úlcera péptica, síndrome de Zollinger-Ellison, erradicación de H. pylori (combinado).'
),
(
  'Loratadina',
  'Loratadina',
  'Antihistamínicos',
  'Tabletas 10mg, Jarabe 1mg/ml.',
  '10mg una vez al día.',
  '2-12 años: 5mg/día si peso <30kg, 10mg/día si peso ≥30kg.',
  'Hipersensibilidad a la loratadina.',
  'Somnolencia leve, cefalea, sequedad de boca. Raramente: taquicardia, malestar gastrointestinal.',
  'Cetoconazol, eritromicina: aumentan niveles de loratadina. No potenciar significativamente el alcohol.',
  'Rinitis alérgica, urticaria crónica, conjuntivitis alérgica, prurito.'
),
(
  'Metformina',
  'Metformina clorhidrato',
  'Antidiabéticos',
  'Tabletas 500mg, 850mg, 1000mg.',
  '500-850mg 2-3 veces al día con las comidas. Máximo 2550mg/día.',
  'No recomendado en menores de 10 años. 10-16 años: 500mg/día, titular hasta máximo 2000mg/día.',
  'Insuficiencia renal grave (TFG<30), cetoacidosis diabética, insuficiencia hepática, alcoholismo.',
  'Diarrea, náuseas, vómitos, flatulencia, dolor abdominal. Raro: acidosis láctica.',
  'Alcohol: aumenta riesgo de acidosis láctica. Contrastantes yodados: suspender 48h. Insulina: riesgo de hipoglucemia.',
  'Diabetes mellitus tipo 2, resistencia a la insulina, síndrome de ovario poliquístico.'
),
(
  'Enalapril',
  'Enalapril maleato',
  'Antihipertensivos',
  'Tabletas 5mg, 10mg, 20mg.',
  '5-40mg al día, en 1-2 dosis. Dosis inicial: 5mg/día.',
  '0.1mg/kg/día. Máximo 0.6mg/kg/día.',
  'Embarazo, estenosis bilateral de arterias renales, angioedema previo por IECAs, hiperpotasemia.',
  'Tos seca, mareos, hipotensión, hiperpotasemia. Raro: angioedema, insuficiencia renal.',
  'Diuréticos ahorradores de K: hiperpotasemia. Litio: aumenta toxicidad. AINEs: reduce efecto antihipertensivo.',
  'Hipertensión arterial, insuficiencia cardíaca, disfunción ventricular izquierda post-infarto.'
),
(
  'Diclofenaco',
  'Diclofenaco sódico',
  'Antiinflamatorios',
  'Tabletas 50mg, gel tópico 1%, inyectable 75mg/3ml.',
  '50mg cada 8-12 horas. Máximo 150mg/día.',
  '1-3mg/kg/día divididos en 2-3 dosis.',
  'Úlcera péptica activa, insuficiencia renal/hepática grave, asma, tercer trimestre embarazo.',
  'Dispepsia, náuseas, cefalea, mareos. Raro: hepatotoxicidad, sangrado GI, reacciones cutáneas graves.',
  'Anticoagulantes: mayor riesgo sangrado. Litio: aumenta niveles. Diuréticos: reduce su efecto.',
  'Artritis reumatoide, osteoartritis, espondilitis anquilosante, dolor postoperatorio, cólico renal.'
),
(
  'Azitromicina',
  'Azitromicina dihidrato',
  'Antibióticos',
  'Tabletas 250mg, 500mg. Suspensión 200mg/5ml.',
  '500mg día 1, luego 250mg días 2-5. O 500mg/día por 3 días.',
  '10mg/kg/día por 3 días (día 1), o 10mg día 1 seguido de 5mg/día 4 días más.',
  'Hipersensibilidad a macrólidos, insuficiencia hepática grave, prolongación QT.',
  'Diarrea, náuseas, dolor abdominal, cefalea. Raro: hepatotoxicidad, arritmias cardíacas.',
  'Antiácidos con aluminio/magnesio: reducir absorción. Digoxina: aumenta niveles. Warfarina: puede aumentar INR.',
  'Infecciones respiratorias, otitis media, faringitis, infecciones de piel, neumonía adquirida en la comunidad.'
),
(
  'Salbutamol',
  'Salbutamol sulfato',
  'Broncodilatadores',
  'Inhalador 100mcg/dosis, jarabe 2mg/5ml, nebulización 5mg/ml.',
  '1-2 inhalaciones cada 4-6 horas según necesidad.',
  'Nebulización: 0.15mg/kg (mín 1.25mg, máx 5mg) cada 4-6 horas.',
  'Taquiarritmias, hipertiroidismo no controlado, hipersensibilidad.',
  'Tremor fino, cefalea, taquicardia, palpitaciones. Raro: hipopotasemia, broncoespasmo paradójico.',
  'Betabloqueantes: antagonizan efecto. Diuréticos: aumentan hipopotasemia. IMAO: riesgo cardiovascular.',
  'Asma bronquial, EPOC, broncoespasmo inducido por ejercicio, bronquitis con componente obstructivo.'
),
(
  'Metoclopramida',
  'Metoclopramida clorhidrato',
  'Antieméticos',
  'Tabletas 10mg, inyectable 10mg/2ml, gotas.',
  '10mg cada 8 horas, antes de las comidas. Máximo 30mg/día.',
  '0.1-0.15mg/kg cada 8 horas. Máximo 0.5mg/kg/día.',
  'Feocromocitoma, obstrucción mecánica intestinal, epilepsia, tratamiento con neurolépticos.',
  'Somnolencia, diarrea, síntomas extrapiramidales (especialmente en jóvenes). Raro: síndrome neuroléptico maligno.',
  'Neurolépticos: aumentan síntomas extrapiramidales. Insulina: altera absorción de glucosa. Digoxina: reduce absorción.',
  'Náuseas y vómitos, gastroparesia, reflujo gastroesofágico, preparación para estudios radiológicos.'
),
(
  'Clopidogrel',
  'Clopidogrel besilato',
  'Antiagregantes plaquetarios',
  'Tabletas 75mg.',
  '75mg una vez al día. Dosis de carga: 300-600mg en síndrome coronario agudo.',
  'No recomendado en niños.',
  'Sangrado activo, insuficiencia hepática grave, hipersensibilidad.',
  'Sangrado, diarrea, dolor abdominal, dispepsia. Raro: púrpura trombocitopénica, neutropenia.',
  'Omeprazol: reduce efecto antiagregante. AINEs: mayor riesgo sangrado. Warfarina: mayor riesgo hemorrágico.',
  'Prevención de eventos cardiovasculares en pacientes con infarto reciente, ACV reciente, enfermedad arterial periférica.'
),
(
  'Ciprofloxacino',
  'Ciprofloxacino',
  'Antibióticos',
  'Tabletas 250mg, 500mg, 750mg.',
  '250-750mg cada 12 horas según tipo de infección.',
  '10-20mg/kg cada 12 horas. Máximo 750mg/dosis.',
  'Embarazo, lactancia, niños en crecimiento (relativo), hipersensibilidad a quinolonas, tendinitis previa.',
  'Náuseas, diarrea, cefalea, mareos, fotosensibilidad. Raro: tendinitis, rotura tendinosa, neuropatía periférica.',
  'Antiácidos: reducen absorción. Teofilina: aumenta niveles. Warfarina: aumenta efecto anticoagulante.',
  'Infecciones urinarias complicadas, prostatitis, infecciones gastrointestinales, infecciones de piel, ántrax.'
),
(
  'Atorvastatina',
  'Atorvastatina cálcica',
  'Hipolipemiantes',
  'Tabletas 10mg, 20mg, 40mg, 80mg.',
  '10-80mg una vez al día, preferiblemente por la noche.',
  '10-17 años: 10mg/día. Máximo 20mg/día.',
  'Enfermedad hepática activa, embarazo, lactancia, hipersensibilidad.',
  'Mialgia, artralgia, diarrea, dispepsia. Raro: rabdomiólisis, hepatotoxicidad, diabetes tipo 2.',
  'Gemfibrozil: aumenta riesgo de miopatía. Ciclosporina: aumentar dosis con precaución. Eritromicina: riesgo de miopatía.',
  'Hipercolesterolemia, hipertrigliceridemia, prevención cardiovascular en pacientes de riesgo.'
),
(
  'Prednisona',
  'Prednisona',
  'Corticosteroides',
  'Tabletas 5mg, 20mg, 50mg.',
  '5-60mg/día según indicación. Dosis altas en crisis: 1-2mg/kg/día.',
  '1-2mg/kg/día en dosis divididas.',
  'Infecciones fúngicas sistémicas, hipersensibilidad. Precaución: diabetes, HTA, osteoporosis.',
  'Hiperglucemia, retención de líquidos, aumento de peso, insomnio. Uso prolongado: osteoporosis, supresión adrenal.',
  'AINEs: mayor riesgo de úlcera GI. Anticoagulantes: altera efecto. Antidiabéticos: reduce su efecto.',
  'Enfermedades inflamatorias, asma, alergias graves, enfermedades autoinmunes, trasplantes.'
);
